import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BaseLayout from "@/components/BaseLayout";

import { getServerSession } from "next-auth";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  console.log("session :", session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <BaseLayout>{children}</BaseLayout>
        </Providers>
      </body>
    </html>
  );
}
